import antfu from '@antfu/eslint-config'

export default antfu({
  rules: {
    'no-console': 'off',
    'no-bitwise': 'off',
    'no-unused-vars': 'off',
    'no-async-promise-executor': 'warn',
    'import/no-unresolved': 'off',
    'import/extensions': 'off',
    'import/no-extraneous-dependencies': 'off',
    'vue/multi-word-component-names': 'off',
    '@typescript-eslint/ban-ts-comment': 0,
    '@typescript-eslint/no-explicit-any': 0,
    '@typescript-eslint/no-this-alias': ['off'],
    'node/prefer-global/process': 'off',
    'unicorn/no-new-array': 'off',
    'vue/no-unused-refs': 'warn',
    'vue/custom-event-name-casing': 'off',
    'ts/no-unused-expressions': 'warn',
    'unused-imports/no-unused-vars': 'warn',
    'perfectionist/sort-imports': ['error', {
      type: 'line-length',
      order: 'asc',
      fallbackSort: {
        type: 'alphabetical',
        order: 'asc',
      },
      sortSideEffects: true,
      maxLineLength: 100,
      internalPattern: ['^@/.*'],
      newlinesBetween: 'ignore',
      groups: [
        ['side-effect-style', 'side-effect', 'style'],
        'builtin-type',
        ['vue-type', 'external-type'],
        'internal-type',
        ['parent-type', 'sibling-type', 'index-type'],
        'builtin',
        'vue',
        'vue-router',
        'pinia',
        'element',
        'external',
        'internal',
        ['parent', 'sibling', 'index'],
        'object',
        'unknown',
      ],
      customGroups: {
        value: {
          'vue': ['^vue$'],
          'vue-router': ['^vue-router$', '^@vueuse/router$'],
          'pinia': ['^pinia$', '^@vueuse/pinia$'],
          'element': ['^element-plus$', '^@element-plus/.*$'],
          'utils': [
            '^lodash',
            '^axios$',
            '^dayjs$',
            '^@vueuse/core$',
            '^@vueuse/.*$',
          ],
        },
        type: {
          'vue-type': [
            '^vue$',
            '^vue-router$',
            '^pinia$',
            '^@vue/.*$',
            '^@vueuse/.*$',
          ],
        },
      },
    }],
  },
  ignores: ['helm', 'node_modules', '.DS_Store', '*.local', '*.d.ts', 'public/**/**', '*.md', 'src/utils/base64.ts', 'simple-mind-map'],
  yaml: false,
  formatters: {
    css: true,
    html: true,
    markdown: 'prettier',
  },
})
